version: "3.4"

services:
  helloDocker:
    image: example
    deploy:
      replicas: 1 
    ports:
      - 8080:8080
   
  etcd:
    image: socat

  real_etcd:
    image: etcd
    environment:  
      - ENVIRONMENT=dev
    volumes:
      - type: tmpfs
        target: /data
